version: 0.2

phases:
  pre_build:
    commands:
      - docker build --target setup -t uniqys-nuxt-sandbox:setup .
      - docker build --target deploy -t uniqys-nuxt-sandbox:deploy .
      - docker build --target prod -t uniqys-nuxt-sandbox:prod .

