version: "3"
services:
  dapp:
    image: uniqys-nuxt-sandbox:dapp
    build:
      context: .
      dockerfile: docker/dapp/Dockerfile

  deploy:
    image: uniqys-nuxt-sandbox:deploy
    build:
      context: .
      dockerfile: docker/deploy/Dockerfile
    environment:
      AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
      AWS_CONTAINER_CREDENTIALS_RELATIVE_URI: $AWS_CONTAINER_CREDENTIALS_RELATIVE_URI
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
      - /app/node_modules
      - /app/aws/node_modules
      - /app/aws/bin